version: '3'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openmrs

  openmrs-server:
    build: ./
    depends_on:
      - db
    image: ubuntu:latest
    ports:
      - '18080:8080'
      - '10080:80'
      - '10443:443'
      - '10022:22'