version: '2'

services:
  proxy:
    image: linuxserver/letsencrypt
    container_name: proxy
    cap_add:
      - NET_ADMIN
    environment:
      URL: ${URL}
      VALIDATION: http
      PGID: 1000
      PUID: 1000
      TZ: ${TZ}
      EMAIL: ${EMAIL}
      STAGING: ${STAGING}
    volumes:
      - proxy:/config
      - ./proxy/openmrs.conf:/config/nginx/proxy-confs/openmrs.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  db:
    image: mysql:5.6
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    labels:
      - backup_target

    volumes:
      - openmrs-database:/var/lib/mysql

  refapp:
    depends_on:
      - db
    build: ./refapp
    ports:
      - 8080:8080
    links:
      - db:database
    environment:
      DB_HOST: database
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CREATE_TABLES: ${DB_CREATE_TABLES}
      MODULE_WEB_ADMIN: ${MODULE_WEB_ADMIN}
      OPENMRS_ADMIN_PASSWORD: ${OPENMRS_ADMIN_PASSWORD}  # Not necessary in the load-db context
      TZ: ${TZ}
    volumes:
      - document-upload:/usr/local/tomcat/.OpenMRS/Document

volumes:
  openmrs-database:
  document-upload:
  proxy:

