version: '2'

services:

  refapp:
    build: ./refapp
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CREATE_TABLES: ${DB_CREATE_TABLES}
      MODULE_WEB_ADMIN: ${MODULE_WEB_ADMIN}
      OPENMRS_ADMIN_PASSWORD: ${OPENMRS_ADMIN_PASSWORD}

  proxy:
    depends_on:
      - refapp
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    links:
      - refapp:reference_application

    environment:
      URL: ${URL}
      VALIDATION: http
      PGID: 1000
      PUID: 1000
      TZ: ${TZ}
      EMAIL: ${EMAIL}
      STAGING: ${STAGING}

    volumes:
      - ./proxy/default:/config/nginx/site-confs/default

volumes:
  nginx-proxy-conf: