version: '3'

services:
  db:
    image: mysql:5.6
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    labels:
      - backup_target

    volumes:
      - ./db:/docker-entrypoint-initdb.d

  refapp:
    depends_on:
      - db
    build: ./refapp
    image: 127.0.0.1:5000/refapp
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CREATE_TABLES: ${DB_CREATE_TABLES}
      MODULE_WEB_ADMIN: ${MODULE_WEB_ADMIN}
      OPENMRS_ADMIN_PASSWORD: unused  # Not necessary in the load-db context
      TZ: ${TZ}

  proxy:
    depends_on:
      - refapp
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443

    environment:
      URL: ${URL}
      VALIDATION: http
      PGID: 1000
      PUID: 1000
      TZ: ${TZ}
      EMAIL: ${EMAIL}
      STAGING: ${STAGING}

    volumes:
      - ./proxy/default:/config/nginx/site-confs/default

