version: '2'

services:
  db:
    image: mysql:5.6
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  refapp:
    depends_on:
      - db
    image: isears/refapp-production:2.7.0
    ports:
      - 8080:8080
    links:
      - db:database
    environment:
      DB_HOST: database
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CREATE_TABLES: ${DB_CREATE_TABLES}
      MODULE_WEB_ADMIN: ${MODULE_WEB_ADMIN}
      OPENMRS_ADMIN_PASSWORD: ${OPENMRS_ADMIN_PASSWORD}

  proxy:
    depends_on:
      - refapp
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    links:
      - refapp:reference_application

    environment:
      URL: ${URL}
      VALIDATION: http
      PGID: 1000
      PUID: 1000
      TZ: ${TZ}
      EMAIL: ${EMAIL}
      STAGING: ${STAGING}

    volumes:
      - ./proxy/default:/config/nginx/site-confs/default

volumes:
  nginx-proxy-conf: