version: '2'
# Connect to an existing DB
services:

  refapp:
    build: ./refapp
    ports:
      - 8080:8080
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CREATE_TABLES: ${DB_CREATE_TABLES}
      MODULE_WEB_ADMIN: ${MODULE_WEB_ADMIN}
      OPENMRS_ADMIN_PASSWORD: ${OPENMRS_ADMIN_PASSWORD}
      TZ: ${TZ}