# Testing only: starts openmrs without nginx proxy
version: '2'

services:
  db:
    image: mysql:5.6
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    
    volumes:
      - ./util/backup.sh:/etc/cron.daily/backup.sh
      - ${BACKUPS_PATH}:/backups

  refapp:
    depends_on:
      - db
    build: ./refapp
    links:
      - db:database

    ports:
      - 8080:8080
    
    environment:
      DB_HOST: database
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CREATE_TABLES: ${DB_CREATE_TABLES}
      MODULE_WEB_ADMIN: ${MODULE_WEB_ADMIN}
      OPENMRS_ADMIN_PASSWORD: ${OPENMRS_ADMIN_PASSWORD}
      TZ: ${TZ}

