- name: set mysql config options
  debconf: 
    name: mysql-server-5.6
    question: "{{item}}"
    value: "{{ db_root_password | default('root') }}"
    vtype: password
  with_items:
    - root_password
    - root_password_again

- name: Install mysql-56 and dependencies
  apt: 
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - mysql-server-5.6
    - libmysqlclient-dev
    - python-pip
    - python-dev
    
- name: Install python mysql libraries
  pip:
    name: MySQL-python
    
- name: Allow remote access to db
  mysql_user:
    name: "{{ db_user | default('openmrs') }}"
    host: '%'
    password: "{{ db_password | default('openmrs') }}"
    priv: '*.*:ALL'
    state: present
  notify: Restart mysql
    
- name: Copy mysql config
  copy:
    src: my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: Restart mysql

# TODO: if db connection errors come up later may have to add short pause here
    
    