- name: Add additional repositories
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install apt dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - apache2
    - tomcat7
    - unzip
    - python3-pip
    - python-pip
    - libapache2-mod-jk
    - python-certbot-apache

- name: Install python libraries for scripts
  pip:
    name: requests
    
- name: Copy custom tomcat defaults
  copy:
    src: tomcat7-defaults
    dest: /etc/default/tomcat7
    owner: root
    group: root
    mode: 0644
    
- name: Copy custom tomcat server settings
  copy:
    src: tomcat-server.xml
    dest: /etc/tomcat7/server.xml
    owner: root
    group: tomcat7
    mode: 0644
        
# TODO: make version into variable
- name: Create OpenMRS directories
  file:
    path: "{{item}}"
    owner: tomcat7
    group: tomcat7
    state: directory
    mode: 0755
  with_items:
    - /var/lib/OpenMRS
    - /var/lib/tomcat7/webapps/openmrs
    
- name: Download OpenMRS bundle
  get_url:
    url: https://sourceforge.net/projects/openmrs/files/releases/OpenMRS_2.4/openmrs-2.4-modules.zip
    dest: /root/openmrs-2.4-modules.zip
    timeout: 60 # Sourceforge is slow

- name: Unzip OpenMRS Bundle
  unarchive:
    src: /root/openmrs-2.4-modules.zip
    dest: /root
    remote_src: yes
    
- name: Move war to tomcat dir
  copy:
    src: /root/referenceapplication-package-2.4/openmrs-1.11.6.war
    dest: /var/lib/tomcat7/webapps/openmrs.war
    mode: 0644
    owner: tomcat7
    remote_src: yes

- name: Restart tomcat
  service:
    name: tomcat7
    state: restarted
    
- name: Unpack war file
  unarchive:
    src: /var/lib/tomcat7/webapps/openmrs.war
    dest: /var/lib/tomcat7/webapps/openmrs/
    copy: no
    mode: 0755
    owner: tomcat7
    group: tomcat7
    
- name: Ensure modules dir exists
  file:
    path: /var/lib/OpenMRS/modules
    state: directory
    owner: tomcat7
    group: tomcat7
    mode: 0755
    
# Unfortunately no good way to make copy with_fileglob work remotely
- name: Install omods
  shell: "cp /root/referenceapplication-package-2.4/*.omod /var/lib/OpenMRS/modules/"
  
- name: Install patientlist omod
  get_url:
    url: https://github.com/fortitudoinc/patientlist/raw/master/omod/target/patientlist-1.0.0-SNAPSHOT.omod
    dest: /var/lib/OpenMRS/modules/patientlist-1.0.0-SNAPSHOT.omod
    owner: tomcat7
    group: tomcat7
    mode: 0644

- name: Chnage omod permissions
  shell: "chown tomcat7:tomcat7 /var/lib/OpenMRS/modules/*"
    
- name: Remove default index.html
  file:
    path: /var/lib/tomcat7/webapps/ROOT/index.html
    state: absent
    
- name: Redirect root requests to openmrs site
  copy:
    src: index.jsp
    dest: /var/lib/tomcat7/webapps/ROOT/index.jsp
    owner: root
    group: root
    mode: 0644
    


# TODO: Make these options ansible (vault?) variables    
- name: Execute setup script
  script: >
   scripts/openmrs-initial-setup.py 
   {{ mysql_host | default('192.168.50.11') }} 
   {{ db_user | default('openmrs') }} 
   {{ db_password | default('openmrs') }} 
   {{ demo_data | default('no') }} 
   {{ admin_password | default('Admin123') }}
    
- name: Copy mod_jk conf
  file:
    src: mod-jk.properties
    path: /etc/libapache2-mod-jk/workers.properties
    owner: root
    group: root
    mode: 0644
    
- name: Configure ssl with certbot
  command: certbot --apache -d {{ server_name }} -n --agree-tos --email {{ admin_email }}
  
- name: Copy apache site conf
  template:
    src: "{{item}}"
    dest: "/etc/apache2/sites-available/{{ server_name }}-{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - apache-site.conf
    - apache-site-ssl.conf
    
- name: Copy apache ports conf
  template:
    src: apache-ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: 0644
  
- name: Disable any default/previously configured sites
  command: a2dissite *
  
- name: enable apache mods
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - rewrite
    - jk
    - ssl
    
- name: Enable sites
  command: "a2ensite {{item}}"
  with_items:
    - "{{ server_name }}-apache-site"
    - "{{ server_name }}-apache-site-ssl"

- name: Restart apache
  service:
    name: apache2
    state: restarted
    