- name: Add additional repositories
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install apt dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - apache2
    - tomcat7
    - unzip
    - python3-pip
    - libapache2-mod-jk
    - python-certbot-apache

- name: Install python libraries for scripts
  pip:
    name: requests
    
- name: Copy custom tomcat defaults
  copy:
    src: tomcat7-defaults
    dest: /etc/default/tomcat7
    owner: root
    group: root
    mode: 0644
    
- name: Copy custom tomcat server settings
  copy:
    src: tomcat-server.xml
    dest: /etc/tomcat7/server.xml
    owner: root
    group: tomcat7
    mode: 0644
        
# TODO: make version into variable
- name: Download war file
  get_url:
    url: https://sourceforge.net/projects/openmrs/files/releases/OpenMRS_Reference_Application_2.6.1/openmrs.war
    dest: /var/lib/tomcat7/webapps/openmrs.war
    mode: 0644
    owner: tomcat7
    timeout: 60 # Sourceforge is slow
    
- name: Restart tomcat
  service:
    name: tomcat7
    state: restarted
    
- name: Unpack war file
  unarchive:
    src: /var/lib/tomcat7/webapps/openmrs.war
    dest: /var/lib/tomcat7/webapps/openmrs/
    copy: no
    mode: 0755
    owner: tomcat7
    group: tomcat7
    
- name: Create OpenMRS directory
  file:
    path: /var/lib/OpenMRS
    owner: tomcat7
    group: tomcat7
    state: directory
    mode: 0755
    
- name: Remove default index.html
  file:
    path: /var/lib/tomcat7/webapps/ROOT/index.html
    state: absent
    
- name: Redirect root requests to openmrs site
  copy:
    src: index.jsp
    dest: /var/lib/tomcat7/webapps/ROOT/index.jsp
    owner: root
    group: root
    mode: 0644
    


# TODO: Make these options ansible (vault?) variables    
- name: Execute setup script
  script: >
   scripts/openmrs-initial-setup.py 
   {{ mysql_host | default('192.168.50.11') }} 
   {{ db_user | default('openmrs') }} 
   {{ db_password | default('openmrs') }} 
   {{ demo_data | default('yes') }} 
   {{ admin_password | default('Admin123') }}
    
- name: Copy mod_jk conf
  file:
    src: mod-jk.properties
    path: /etc/libapache2-mod-jk/workers.properties
    owner: root
    group: root
    mode: 0644
    
- name: Configure ssl with certbot
  command: certbot --apache -d {{ server_name }} -n --agree-tos --email {{ admin_email }}
  
- name: Copy apache site conf
  template:
    src: "{{item}}"
    dest: "/etc/apache2/sites-available/{{ server_name }}-{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - apache-site.conf
    - apache-site-ssl.conf
    
- name: Copy apache ports conf
  template:
    src: apache-ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: 0644
  
- name: Disable any default/previously configured sites
  command: a2dissite *
  
- name: enable apache mods
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - rewrite
    - jk
    - ssl
    
- name: Enable sites
  command: "a2ensite {{item}}"
  with_items:
    - "{{ server_name }}-apache-site"
    - "{{ server_name }}-apache-site-ssl"

- name: Restart apache
  service:
    name: apache2
    state: restarted
    